enabled: true

single-use-net:
 enabled: true
 crafting:
  enabled: true
  recipe:
   slot:
    0:
     item:
     amount:
     enchantments:
     nbt:
    1:
     item:
     amount:
     enchantments:
     nbt:
    2:
     item:
     amount:
     enchantments:
     nbt:
    3:
     item:
     amount:
     enchantments:
     nbt:
    4:
     item:
     amount:
     enchantments:
     nbt:
    5:
     item:
     amount:
     enchantments:
     nbt:
    6:
     item:
     amount:
     enchantments:
     nbt:
    7:
     item:
     amount:
     enchantments:
     nbt:
    8:
     item:
     amount:
     enchantments:
     nbt:

multi-use-net:
 enabled: true
 crafting:
  enabled: true
  recipe:
   slot:
    0:
     item:
     amount:
     enchantments:
     nbt:
    1:
     item:
     amount:
     enchantments:
     nbt:
    2:
     item:
     amount:
     enchantments:
     nbt:
    3:
     item:
     amount:
     enchantments:
     nbt:
    4:
     item:
     amount:
     enchantments:
     nbt:
    5:
     item:
     amount:
     enchantments:
     nbt:
    6:
     item:
     amount:
     enchantments:
     nbt:
    7:
     item:
     amount:
     enchantments:
     nbt:
    8:
     item:
     amount:
     enchantments:
     nbt: